services:
  localsecret:
    #image: ghcr.io/scrtlabs/localsecret:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - localsecret_data:/root/
    ports:
      - 9091:9091
      - 26657:26657
      - 1317:1317
      - 5000:5000
      - 26656:26656
volumes:
  localsecret_data:
    driver: local
    driver_opts:
      type: none
      device: ~/sn-docker/data
      o: bind